name: Integration tests
on: [push]
jobs:
  runIntegrationTests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup venom web
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - name: Setup Chrome
        uses: ./.github/actions/setup-chrome
        with:
          version: 112
      - name: Setup venom
        uses: actions/checkout@v3
        with:
          repository: ovh/venom
          ref: v1.2.0-beta.1
          path: venom
      - name: Build venom
        run: |
          echo ${{ matrix.version }}
          cd venom/cmd/venom
          go version
          make build OS=linux ARCH=amd64
          mv dist/venom.linux-amd64 ../../../venomWeb/venom
          cd ../../../venomWeb
          cp /opt/chromedriver/chromedriver .
          ./venom --format=xml run tests/chrome/core.yml
          echo $?
          ls -la $GOROOT