name: Integration tests
on: [push]
jobs:
  runIntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - name: Set up Chrome
        uses: logikal-io/install-chrome@v1
        with:
          version: 113.0.5672.63-1
      - name: Set up venom web
        uses: actions/checkout@v3
        with:
          path: venomWeb
      - name: Set up venom
        uses: actions/checkout@v3
        with:
          repository: ovh/venom
          ref: v1.2.0-beta.1
          path: venom
      - name: Build venom
        run: |
          echo $GOROOT
          cd venom/cmd/venom
          go version
          make build OS=linux ARCH=amd64
          mv dist/venom.linux-amd64 ../../../venomWeb/venom
          cd ../../../venomWeb
          ls -la
          venom --format=xml run venomWeb/tests/chrome/core.yml
          ls -la $GOROOT