name: Integration tests
on: [push]
jobs:
  runIntegrationTests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup venom web
        uses: actions/checkout@v3
        with:
          path: venomWeb
          ref: develop-tests
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - name: Setup Chrome
        uses: ./venomWeb/.github/actions/setup-chrome
        with:
          version: 112
      - name: Setup Chrome Driver
        uses: ./venomWeb/.github/actions/setup-chromedriver
        with:
          version: 112
      - name: Setup venom
        uses: actions/checkout@v3
        with:
          repository: ovh/venom
          ref: v1.2.0-beta.1
          path: venom
      - name: Build venom
        uses: ./venomWeb/.github/actions/setup-venom
        with:
          venomVersion: v1.2.0-beta.1
          venomWebVersion: develop-tests
          plateform: ${{ matrix.os }}
      - name: Run venom
        run: |
          mv venom/cmd/venom/dist venom venomWeb/venom
          cd ../../../venomWeb
          cp /opt/chromedriver/chromedriver ./chromedriver
          ./venom -vvv --format=xml run tests/chrome/core.yml